copy MainCV.pas w:\CVT340\MainCV.pas
copy UFormDebug.dfm w:\CVT340\UFormDebug.dfm
copy UFormDebug.pas w:\CVT340\UFormDebug.pas
copy UFormEntry.dfm w:\CVT340\UFormEntry.dfm
copy UFormEntry.pas w:\CVT340\UFormEntry.pas
copy UFormHelp.dfm w:\CVT340\UFormHelp.dfm
copy UFormHelp.pas w:\CVT340\UFormHelp.pas
copy UFormMain.dfm w:\CVT340\UFormMain.dfm
copy UFormMain.pas w:\CVT340\UFormMain.pas
copy UFormMessage.dfm w:\CVT340\UFormMessage.dfm
copy UFormMessage.pas w:\CVT340\UFormMessage.pas
copy UFormSearch.dfm w:\CVT340\UFormSearch
copy UFormSearch.pas w:\CVT340\UFormSearch.pas
copy UFormSetPassword.dfm w:\CVT340\UFormSetPassword.dfm
copy UFormSetPassword.pas w:\CVT340\UFormSetPassword.pas
copy UFormSettingsScreen.dfm w:\CVT340\UFormSettingsScreen.dfm
copy UFormSettingsScreen.pas w:\CVT340\UFormSettingsScreen.pas
copy UFormSettingsServer.dfm w:\CVT340\UFormSettingsServer.dfm
copy UFormSettingsServer.pas w:\CVT340\UFormSettingsServer.pas
copy UFormSettingSSH.dfm w:\CVT340\UFormSettingSSH.dfm
copy UFormSettingSSH.pas w:\CVT340\UFormSettingSSH.pas
copy WinUnix.pas w:\CVT340\WinUnix.pas
copy Prm.ini w:\CVT340\Prm.ini
copy VT340.cfg w:\CVT340\VT340.cfg
copy VT340.dof w:\CVT340\VT340.dof
copy VT340.dpr w:\CVT340\VT340.dpr
copy VT340.exe w:\CVT340\VT340.exe
copy VT340.res w:\CVT340\VT340.res
